###
GET http://127.0.0.1:8000/api/chat/Who%20are%20you
###
POST http://127.0.0.1:8000/api/add_or_modify_entry
Content-Type: application/json

{
  "entry_text": "Today I went for a walk",
  "entry_date": "2025-11-20"
}
###
GET http://127.0.0.1:8000/api/diary/2025-11-01